version: '3.8'

services:
  #databasec section
  teduidentitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: teduidentitydb
    environment:
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"
    restart: always
    volumes:
        - tedu_identity_sqlserver_data:/var/opt/mssql
    ports:
        - "1436:1433"

  #api section
  tedu.identity.api:
    image: ${DOCKER_REGISTRY-}tedu-identity-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: TeduMicroservice.IDP/Dockerfile
    container_name: tedu.identity.api
    environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ASPNETCORE_URLS=http://+:80
         - "ConnectionStrings:IdentitySqlConnection=Server=teduidentitydb;Database=TeduIdentity;User Id=sa;Password=Passw0rd!;Multipleactiveresultsets=true"
         - "IdentityServer:BaseUrl=http://localhost:6001"   
         - "IdentityServer:IssuerUri=http://tedu.identity.api"
    depends_on:
        - teduidentitydb    
    ports:
        - "6001:80"
    restart: always

networks:
  default:
    external:
        name: tedu_microservice
volumes:
  tedu_identity_sqlserver_data:
    external: false